<script lang="ts" setup>
import { onMounted, ref } from 'vue'

type Step = { step_id: string; status: string; artifact_ids: string[]; evidence_ids: string[] }
type Event = { event_type: string; timestamp: string }
type TaskSnapshot = { task: { id: string; title: string; goal: string; status: string }, steps: Step[], events: Event[] }
type Workspace = { id: string; name: string; root_path: string }
type Deployment = { id: string; name: string; endpoint: string; model: string; enabled: boolean }
type Capability = { supports_tools: boolean; supports_streaming: boolean; reliable_context_tokens: number }

const tasks = ref<TaskSnapshot[]>([]); const workspaces = ref<Workspace[]>([]); const deployments = ref<Deployment[]>([])
const selected = ref<TaskSnapshot | null>(null); const error = ref(''); const notice = ref(''); const loading = ref(true); const busy = ref(false)
const workspaceName = ref(''); const workspacePath = ref(''); const taskWorkspaceID = ref(''); const taskTitle = ref(''); const taskGoal = ref('')
const deploymentName = ref('Local model'); const deploymentEndpoint = ref('http://127.0.0.1:8080/v1'); const deploymentModel = ref(''); const apiKey = ref(''); const selectedDeploymentID = ref(''); const capability = ref<Capability | null>(null)
const activePanel = ref<'tasks' | 'settings'>('tasks'); const showWorkspaceForm = ref(false); const showTaskForm = ref(false)

function fail(cause: unknown) { error.value = String(cause); notice.value = '' }
async function refresh() {
  loading.value = true; error.value = ''
  try {
    const [taskItems, workspaceItems, deploymentItems] = await Promise.all([window.go.main.App.ListTasks(), window.go.main.App.ListWorkspaces(), window.go.main.App.ListDeployments()])
    tasks.value = taskItems as TaskSnapshot[]; workspaces.value = workspaceItems as Workspace[]; deployments.value = deploymentItems as Deployment[]
    if (!taskWorkspaceID.value && workspaces.value.length) taskWorkspaceID.value = workspaces.value[0].id
    if (!selectedDeploymentID.value && deployments.value.length) selectedDeploymentID.value = deployments.value[0].id
    if (!selected.value && tasks.value.length) selected.value = tasks.value[0]
  } catch (cause) { fail(cause) } finally { loading.value = false }
}
async function createWorkspace() { try { busy.value = true; await window.go.main.App.CreateWorkspace(workspaceName.value, workspacePath.value); workspaceName.value = ''; workspacePath.value = ''; showWorkspaceForm.value = false; notice.value = '工作区已创建'; await refresh() } catch (cause) { fail(cause) } finally { busy.value = false } }
async function createTask() { try { busy.value = true; const item = await window.go.main.App.CreateTask(taskWorkspaceID.value, taskTitle.value, taskGoal.value) as TaskSnapshot; taskTitle.value = ''; taskGoal.value = ''; showTaskForm.value = false; selected.value = item; notice.value = '任务已创建，可选择模型后运行 Agent'; await refresh() } catch (cause) { fail(cause) } finally { busy.value = false } }
async function configureModel() { try { busy.value = true; const item = await window.go.main.App.ConfigureOpenAICompatibleDeployment(deploymentName.value, deploymentEndpoint.value, deploymentModel.value, apiKey.value) as Deployment; selectedDeploymentID.value = item.id; apiKey.value = ''; notice.value = '模型配置已保存；API Key 仅保留在当前应用会话'; await refresh() } catch (cause) { fail(cause) } finally { busy.value = false } }
async function probeModel() { try { busy.value = true; capability.value = await window.go.main.App.ProbeDeployment(selectedDeploymentID.value) as Capability; notice.value = '连通性与能力探测完成' } catch (cause) { fail(cause) } finally { busy.value = false } }
async function selectTask(id: string) { try { selected.value = await window.go.main.App.GetTaskSnapshot(id) as TaskSnapshot } catch (cause) { fail(cause) } }
async function runAgent() { if (!selected.value || !selectedDeploymentID.value) return; try { busy.value = true; await window.go.main.App.GeneratePlan(selected.value.task.id, selectedDeploymentID.value); selected.value = await window.go.main.App.RunAgent(selected.value.task.id, selectedDeploymentID.value) as TaskSnapshot; notice.value = 'Agent 已运行；请查看步骤、证据与事件'; await refresh() } catch (cause) { fail(cause) } finally { busy.value = false } }
onMounted(refresh)
</script>

<template>
  <div class="shell">
    <aside class="sidebar"><div class="brand"><div class="brand-mark">S</div><div><strong>Simpleness</strong><small>Agent Studio</small></div></div><nav><button :class="{active: activePanel === 'tasks'}" @click="activePanel = 'tasks'"><span>◈</span> 任务</button><button :class="{active: activePanel === 'settings'}" @click="activePanel = 'settings'"><span>◌</span> 模型与设置</button></nav><div class="sidebar-bottom"><span class="online-dot"></span> Local Core 已连接</div></aside>
    <main class="workspace">
      <header class="topbar"><div><p class="eyebrow">{{ activePanel === 'tasks' ? 'TASK ORCHESTRATION' : 'MODEL CONTROL PLANE' }}</p><h1>{{ activePanel === 'tasks' ? '任务工作台' : '模型与工作区' }}</h1></div><div class="top-actions"><select v-model="selectedDeploymentID"><option disabled value="">选择模型</option><option v-for="deployment in deployments" :key="deployment.id" :value="deployment.id">{{ deployment.name }} · {{ deployment.model }}</option></select><button class="ghost" :disabled="busy" @click="refresh">↻ 刷新</button></div></header>
      <div v-if="notice" class="toast notice">✓ {{ notice }}</div><div v-if="error" class="toast error">! {{ error }}</div>

      <section v-if="activePanel === 'settings'" class="settings-grid"><article class="surface settings-card"><div class="card-title"><div><span class="icon-block">✦</span><div><h2>模型配置</h2><p>OpenAI-compatible Runtime</p></div></div><span class="chip">Session key</span></div><form class="stack" @submit.prevent="configureModel"><label>配置名称<input v-model="deploymentName" required placeholder="例如：本地 Qwen"></label><label>Base URL<input v-model="deploymentEndpoint" required placeholder="http://127.0.0.1:8080/v1"></label><label>模型 ID<input v-model="deploymentModel" required placeholder="例如：qwen3"></label><label>API Key <span>可选，仅保留于当前会话</span><input v-model="apiKey" type="password" placeholder="sk-... 或留空"></label><button class="primary" :disabled="busy">保存模型配置</button></form></article><article class="surface settings-card"><div class="card-title"><div><span class="icon-block purple">◌</span><div><h2>能力检测</h2><p>验证当前模型 Runtime</p></div></div></div><button class="secondary" :disabled="busy || !selectedDeploymentID" @click="probeModel">探测能力</button><div v-if="capability" class="capabilities"><div><span>工具调用</span><b :class="capability.supports_tools ? 'yes' : 'no'">{{ capability.supports_tools ? '已支持' : '未支持' }}</b></div><div><span>流式输出</span><b :class="capability.supports_streaming ? 'yes' : 'no'">{{ capability.supports_streaming ? '已支持' : '未支持' }}</b></div><div><span>上下文窗口</span><b>{{ capability.reliable_context_tokens || '未报告' }}</b></div></div><p v-else class="muted">保存或选择模型后，执行能力探测。API Key 永远不会写入 SQLite。</p></article><article class="surface settings-card workspace-card"><div class="card-title"><div><span class="icon-block green">⌘</span><div><h2>工作区</h2><p>{{ workspaces.length }} 个已授权本地目录</p></div></div><button class="text-button" @click="showWorkspaceForm = !showWorkspaceForm">+ 添加</button></div><form v-if="showWorkspaceForm" class="stack compact" @submit.prevent="createWorkspace"><input v-model="workspaceName" placeholder="名称（可选）"><input v-model="workspacePath" required placeholder="本地目录绝对路径"><button class="secondary" :disabled="busy">授权该目录</button></form><div class="workspace-list"><div v-for="workspace in workspaces" :key="workspace.id"><b>{{ workspace.name }}</b><small>{{ workspace.root_path }}</small></div><p v-if="!workspaces.length" class="muted">尚未授权任何工作区。</p></div></article></section>

      <section v-else class="agent-layout"><aside class="task-pane surface"><div class="pane-head"><div><h2>任务</h2><span>{{ tasks.length }}</span></div><button class="circle-button" title="新建任务" @click="showTaskForm = !showTaskForm">+</button></div><form v-if="showTaskForm" class="new-task stack compact" @submit.prevent="createTask"><select v-model="taskWorkspaceID" required><option disabled value="">选择工作区</option><option v-for="workspace in workspaces" :key="workspace.id" :value="workspace.id">{{ workspace.name }}</option></select><input v-model="taskTitle" required placeholder="任务标题"><textarea v-model="taskGoal" required placeholder="你希望 Agent 完成什么？"></textarea><button class="primary" :disabled="busy">创建任务</button></form><p v-if="loading" class="muted loading">正在同步任务…</p><div v-else class="task-list"><button v-for="item in tasks" :key="item.task.id" class="task-card" :class="{chosen:selected?.task.id === item.task.id}" @click="selectTask(item.task.id)"><span class="task-state" :class="item.task.status.toLowerCase()"></span><div><b>{{ item.task.title }}</b><small>{{ item.task.goal }}</small><em>{{ item.task.status }}</em></div></button><div v-if="!tasks.length" class="empty-state"><div>✦</div><b>还没有任务</b><small>点击右上角 + 创建第一个任务</small></div></div></aside>
        <section class="agent-canvas surface"><template v-if="selected"><div class="canvas-head"><div><p class="eyebrow">{{ selected.task.status }}</p><h2>{{ selected.task.title }}</h2><p>{{ selected.task.goal }}</p></div><button class="run-button" :disabled="busy || !selectedDeploymentID || selected.task.status !== 'READY'" @click="runAgent"><span>{{ busy ? '◌' : '▶' }}</span> {{ busy ? 'Agent 执行中' : '运行 Agent' }}</button></div><div class="flow"><div class="flow-node done"><span>1</span><div><b>任务已创建</b><small>目标与工作区已写入 Core</small></div></div><div class="flow-line"></div><div class="flow-node" :class="{done:selected.steps.length > 0}"><span>2</span><div><b>计划与执行</b><small>模型生成受控只读计划</small></div></div><div class="flow-line"></div><div class="flow-node" :class="{done:selected.task.status === 'COMPLETED'}"><span>3</span><div><b>验证证据</b><small>Artifact、Evidence、FinalReport</small></div></div></div><div class="section-label">步骤执行</div><div class="steps"><div v-for="step in selected.steps" :key="step.step_id" class="execution-step"><div class="step-icon" :class="step.status.toLowerCase()">✓</div><div><b>{{ step.step_id }}</b><p>{{ step.status }}</p></div><div class="step-metrics"><span>▣ {{ step.artifact_ids.length }} Artifacts</span><span>◇ {{ step.evidence_ids.length }} Evidence</span></div></div><div v-if="!selected.steps.length" class="empty-execution"><span>◎</span><p>任务等待执行。选择模型后点击“运行 Agent”。</p></div></div></template><div v-else class="blank-canvas"><div class="blank-symbol">✦</div><h2>选择一个任务</h2><p>在左侧选择任务，查看 Agent 的计划、执行与证据。</p></div></section>
        <aside class="activity-pane surface"><div class="pane-head"><div><h2>活动</h2><span>LIVE</span></div></div><div v-if="selected" class="timeline"><div v-for="event in selected.events.slice().reverse()" :key="event.timestamp + event.event_type" class="timeline-event"><span></span><div><b>{{ event.event_type.replaceAll('_', ' ') }}</b><small>{{ event.timestamp }}</small></div></div><div v-if="!selected.events.length" class="muted">暂无事件。</div></div><div v-else class="muted">选择任务后显示审计事件。</div></aside>
      </section>
    </main>
  </div>
</template>
