<script lang="ts" setup>
import { computed, nextTick, onMounted, ref } from 'vue'

type Step = { step_id: string; status: string; artifact_ids: string[]; evidence_ids: string[]; last_error_code?: string }
type Event = { event_type: string; timestamp: string; sequence: number }
type PlanStep = { step_id: string; title: string; goal: string; allowed_tools: string[] }
type Plan = { plan_id: string; revision: number; summary: string; steps: PlanStep[] }
type TaskSnapshot = { task: { id: string; title: string; goal: string; status: string }, plan: Plan, steps: Step[], events: Event[] }
type Workspace = { id: string; name: string; root_path: string }
type Deployment = { deployment_id: string; name: string; endpoint: string; model: string }
type Capability = { supports_tools: boolean; supports_streaming: boolean; reliable_context_tokens: number }
type ChatMessage = { role: 'user' | 'agent' | 'system' | 'error'; text: string; task?: TaskSnapshot }

const workspaces = ref<Workspace[]>([]); const deployments = ref<Deployment[]>([]); const tasks = ref<TaskSnapshot[]>([]); const selectedTask = ref<TaskSnapshot | null>(null)
const activePanel = ref<'chat' | 'settings'>('chat'); const workspaceID = ref(''); const deploymentID = ref(''); const prompt = ref(''); const busy = ref(false); const error = ref(''); const notice = ref(''); const messages = ref<ChatMessage[]>([]); const chatBody = ref<HTMLElement | null>(null)
const showWorkspaceForm = ref(false); const workspaceName = ref(''); const workspacePath = ref(''); const deploymentName = ref('Local model'); const deploymentEndpoint = ref('http://127.0.0.1:8080/v1'); const deploymentModel = ref(''); const apiKey = ref(''); const providerTemplate = ref<'local' | 'deepseek' | 'custom'>('local'); const capability = ref<Capability | null>(null)
const storageKey = 'simplenessagent.selected-deployment-id'
const selectedWorkspace = computed(() => workspaces.value.find((item) => item.id === workspaceID.value) ?? null)
const selectedDeployment = computed(() => deployments.value.find((item) => item.deployment_id === deploymentID.value) ?? null)
const canSend = computed(() => !!prompt.value.trim() && !!workspaceID.value && !!deploymentID.value && !busy.value)
function fail(cause: unknown) { error.value = String(cause); notice.value = '' }
function chooseDeployment(id: string) { deploymentID.value = id; capability.value = null; if (id) localStorage.setItem(storageKey, id) }
function applyProviderTemplate() { if (providerTemplate.value === 'deepseek') { deploymentName.value = 'DeepSeek API'; deploymentEndpoint.value = 'https://api.deepseek.com'; deploymentModel.value = 'deepseek-v4-flash' } else if (providerTemplate.value === 'local') { deploymentName.value = 'Local model'; deploymentEndpoint.value = 'http://127.0.0.1:8080/v1'; deploymentModel.value = '' } else { deploymentName.value = '自定义模型'; deploymentEndpoint.value = ''; deploymentModel.value = '' } }
async function scrollChat() { await nextTick(); chatBody.value?.scrollTo({ top: chatBody.value.scrollHeight, behavior: 'smooth' }) }
async function refresh() { try { const [workspaceItems, deploymentItems, taskItems] = await Promise.all([window.go.main.App.ListWorkspaces(), window.go.main.App.ListDeployments(), window.go.main.App.ListTasks()]); workspaces.value = workspaceItems as Workspace[]; deployments.value = deploymentItems as Deployment[]; tasks.value = taskItems as TaskSnapshot[]; if (!workspaceID.value && workspaces.value.length) workspaceID.value = workspaces.value[0].id; if (!deployments.value.some((item) => item.deployment_id === deploymentID.value)) { const saved = localStorage.getItem(storageKey) ?? ''; chooseDeployment(deployments.value.some((item) => item.deployment_id === saved) ? saved : (deployments.value[0]?.deployment_id ?? '')) } } catch (cause) { fail(cause) } }
async function sendMessage() { const text = prompt.value.trim(); if (!canSend.value) return; prompt.value = ''; error.value = ''; messages.value.push({ role: 'user', text }); await scrollChat(); try { busy.value = true; messages.value.push({ role: 'system', text: '正在理解你的需求，生成执行计划…' }); await scrollChat(); const result = await window.go.main.App.SendMessage(workspaceID.value, text, deploymentID.value) as TaskSnapshot; selectedTask.value = result; messages.value = messages.value.filter((item) => item.role !== 'system'); messages.value.push({ role: 'agent', text: result.task.status === 'COMPLETED' ? '已完成任务。执行过程、计划和结果如下。' : `任务已结束，当前状态：${result.task.status}。`, task: result }); notice.value = 'Agent 已完成本轮执行'; await refresh() } catch (cause) { messages.value = messages.value.filter((item) => item.role !== 'system'); messages.value.push({ role: 'error', text: String(cause) }); fail(cause) } finally { busy.value = false; await scrollChat() } }
async function openTask(task: TaskSnapshot) { selectedTask.value = await window.go.main.App.GetTaskSnapshot(task.task.id) as TaskSnapshot; messages.value = [{ role: 'user', text: selectedTask.value.task.goal }, { role: 'agent', text: `已打开任务记录，当前状态：${selectedTask.value.task.status}。`, task: selectedTask.value }]; error.value = ''; notice.value = ''; await scrollChat() }
async function createWorkspace() { try { busy.value = true; const created = await window.go.main.App.CreateWorkspace(workspaceName.value, workspacePath.value) as Workspace; workspaceID.value = created.id; workspaceName.value = ''; workspacePath.value = ''; showWorkspaceForm.value = false; notice.value = '工作区已添加'; await refresh() } catch (cause) { fail(cause) } finally { busy.value = false } }
async function configureModel() { try { busy.value = true; const item = await window.go.main.App.ConfigureOpenAICompatibleDeployment(deploymentName.value, deploymentEndpoint.value, deploymentModel.value, apiKey.value) as Deployment; chooseDeployment(item.deployment_id); apiKey.value = ''; notice.value = '模型已保存'; await refresh() } catch (cause) { fail(cause) } finally { busy.value = false } }
async function probeModel() { try { busy.value = true; capability.value = await window.go.main.App.ProbeDeployment(deploymentID.value) as Capability; notice.value = '模型连接正常，能力检查完成' } catch (cause) { fail(cause) } finally { busy.value = false } }
function runtime(step: PlanStep, task?: TaskSnapshot) { return task?.steps.find((item) => item.step_id === step.step_id) }
onMounted(refresh)
</script>

<template>
  <div class="app-shell"><aside class="sidebar"><div class="brand"><div class="brand-mark">S</div><div><strong>Simpleness</strong><small>智能工作台</small></div></div><nav><button :class="{ active: activePanel === 'chat' }" @click="activePanel = 'chat'"><span>◉</span>对话</button><button :class="{ active: activePanel === 'settings' }" @click="activePanel = 'settings'"><span>◇</span>模型与设置</button></nav><div class="side-section"><p>最近任务</p><button v-for="task in tasks.slice(0, 6)" :key="task.task.id" class="recent-task" @click="openTask(task)">{{ task.task.title }}</button><span v-if="!tasks.length">还没有任务记录</span></div><div class="core-status"><i></i>核心服务已连接</div></aside>
    <main class="main"><header class="topbar"><div><h1>{{ activePanel === 'chat' ? '新对话' : '模型与设置' }}</h1><p>{{ activePanel === 'chat' ? '选择工作区后，直接告诉 Agent 你想完成什么。' : '配置模型、检查连接并管理授权范围。' }}</p></div><div v-if="activePanel === 'chat'" class="header-selects"><select v-model="workspaceID"><option disabled value="">选择工作区</option><option v-for="item in workspaces" :key="item.id" :value="item.id">{{ item.name }}</option></select><select :value="deploymentID" @change="chooseDeployment(($event.target as HTMLSelectElement).value)"><option disabled value="">选择模型</option><option v-for="item in deployments" :key="item.deployment_id" :value="item.deployment_id">{{ item.name }} · {{ item.model }}</option></select></div></header>
      <div v-if="notice" class="banner success">{{ notice }}</div><div v-if="error" class="banner danger">{{ error }}</div>
      <section v-if="activePanel === 'chat'" class="chat-layout"><section class="chat-card card"><div ref="chatBody" class="chat-body"><div v-if="!messages.length" class="welcome"><div>✦</div><h2>今天想完成什么？</h2><p>在已授权工作区中发起一个任务。Agent 会自动规划、使用只读工具执行，并把过程和结果保存在当前对话里。</p><div class="suggestions"><button @click="prompt = '分析当前工作区的项目结构，并总结关键文件和启动方式'">分析项目结构</button><button @click="prompt = '检查工作区中的待办事项和潜在问题'">检查待办事项</button><button @click="prompt = '阅读 README，给出下一步开发建议'">阅读 README</button></div></div><article v-for="(message, index) in messages" :key="index" class="message" :class="message.role"><div class="avatar">{{ message.role === 'user' ? '你' : message.role === 'agent' ? 'S' : '!' }}</div><div class="message-content"><p>{{ message.text }}</p><div v-if="message.task" class="run-result"><div class="result-head"><b>执行结果</b><span :class="message.task.task.status.toLowerCase()">{{ message.task.task.status }}</span></div><p v-if="message.task.plan?.summary">{{ message.task.plan.summary }}</p><div v-for="step in message.task.plan?.steps ?? []" :key="step.step_id" class="result-step"><i :class="runtime(step, message.task)?.status?.toLowerCase() ?? 'pending'"></i><span><b>{{ step.title }}</b><small>{{ step.goal }}</small></span><em>{{ runtime(step, message.task)?.status ?? 'PENDING' }}</em></div><div class="event-summary">{{ message.task.events.length }} 条操作记录 · {{ message.task.steps.reduce((count, step) => count + step.artifact_ids.length, 0) }} 个产物 · {{ message.task.steps.reduce((count, step) => count + step.evidence_ids.length, 0) }} 条证据</div></div></div></article><div v-if="busy" class="thinking"><i></i><i></i><i></i> Agent 正在处理…</div></div><div class="composer"><textarea v-model="prompt" :disabled="busy" @keydown.ctrl.enter.prevent="sendMessage" placeholder="输入任务，例如：分析这个项目的结构并给出改进建议。Ctrl + Enter 发送"></textarea><div><small>{{ selectedWorkspace ? `工作区：${selectedWorkspace.name}` : '请先选择工作区' }} · {{ selectedDeployment ? `模型：${selectedDeployment.name}` : '请先选择模型' }}</small><button class="send-button" :disabled="!canSend" @click="sendMessage">发送</button></div></div></section><aside class="run-panel card"><div class="panel-title"><p>当前执行</p><h2>{{ selectedTask?.task.title ?? '尚未开始' }}</h2></div><template v-if="selectedTask"><span class="status-pill" :class="selectedTask.task.status.toLowerCase()">{{ selectedTask.task.status }}</span><p class="goal">{{ selectedTask.task.goal }}</p><div class="trace"><div v-for="event in selectedTask.events.slice().reverse().slice(0, 12)" :key="event.sequence"><i></i><span><b>{{ event.event_type.replaceAll('_', ' ') }}</b><small>{{ event.timestamp }}</small></span></div></div></template><p v-else class="muted">发送消息后，这里会显示 Agent 的内部规划与操作记录。</p></aside></section>
      <section v-else class="settings"><article class="card settings-card"><div class="section-title"><p>模型配置</p><h2>添加或更新模型</h2></div><form class="form" @submit.prevent="configureModel"><label>快速模板<select v-model="providerTemplate" @change="applyProviderTemplate"><option value="local">本地模型（Ollama / LM Studio / vLLM）</option><option value="deepseek">DeepSeek API</option><option value="custom">自定义 OpenAI-compatible</option></select></label><p v-if="providerTemplate === 'deepseek'" class="hint">已预填 DeepSeek 参数，只需填入 API Key。</p><label>名称<input v-model="deploymentName" required></label><label>Base URL<input v-model="deploymentEndpoint" required></label><label>模型 ID<input v-model="deploymentModel" required></label><label>API Key <small>安全保存于 Windows 凭据管理器</small><input v-model="apiKey" type="password" placeholder="sk-…"></label><button class="send-button" :disabled="busy">保存模型</button></form></article><article class="card settings-card"><div class="section-title"><p>连接检查</p><h2>{{ selectedDeployment?.name ?? '选择一个模型' }}</h2></div><p class="muted">能力检查会验证模型连接、流式输出和工具调用支持情况。</p><button class="secondary-button" :disabled="busy || !deploymentID" @click="probeModel">开始能力检查</button><div v-if="capability" class="capabilities"><span>流式输出 <b>{{ capability.supports_streaming ? '支持' : '未支持' }}</b></span><span>工具调用 <b>{{ capability.supports_tools ? '支持' : '未支持' }}</b></span><span>上下文窗口 <b>{{ capability.reliable_context_tokens || '未报告' }}</b></span></div></article><article class="card workspace-card"><div class="section-title split"><div><p>工作区</p><h2>授权本地目录</h2></div><button class="text-button" @click="showWorkspaceForm = !showWorkspaceForm">添加工作区</button></div><form v-if="showWorkspaceForm" class="workspace-form" @submit.prevent="createWorkspace"><input v-model="workspaceName" placeholder="显示名称（可选）"><input v-model="workspacePath" required placeholder="目录绝对路径"><button class="secondary-button" :disabled="busy">授权</button></form><div class="workspace-list"><div v-for="item in workspaces" :key="item.id"><b>{{ item.name }}</b><small>{{ item.root_path }}</small></div><p v-if="!workspaces.length" class="muted">尚未授权任何目录。</p></div></article></section>
    </main></div>
</template>
