<script lang="ts" setup>
import { computed, onMounted, ref } from 'vue'

type Step = { step_id: string; status: string; artifact_ids: string[]; evidence_ids: string[]; last_error_code?: string }
type Event = { event_type: string; timestamp: string; sequence: number }
type PlanStep = { step_id: string; title: string; goal: string; allowed_tools: string[] }
type Plan = { plan_id: string; revision: number; summary: string; steps: PlanStep[] }
type TaskSnapshot = { task: { id: string; title: string; goal: string; status: string }, plan: Plan, steps: Step[], events: Event[] }
type Workspace = { id: string; name: string; root_path: string }
type Deployment = { deployment_id: string; name: string; endpoint: string; model: string; enabled: boolean }
type Capability = { supports_tools: boolean; supports_streaming: boolean; reliable_context_tokens: number }

const tasks = ref<TaskSnapshot[]>([]); const workspaces = ref<Workspace[]>([]); const deployments = ref<Deployment[]>([])
const selected = ref<TaskSnapshot | null>(null); const error = ref(''); const notice = ref(''); const loading = ref(true); const busy = ref(false); const runPhase = ref<'idle' | 'planning' | 'running'>('idle')
const workspaceName = ref(''); const workspacePath = ref(''); const taskWorkspaceID = ref(''); const taskTitle = ref(''); const taskGoal = ref('')
const deploymentName = ref('Local model'); const deploymentEndpoint = ref('http://127.0.0.1:8080/v1'); const deploymentModel = ref(''); const apiKey = ref(''); const selectedDeploymentID = ref(''); const capability = ref<Capability | null>(null)
const activePanel = ref<'tasks' | 'settings'>('tasks'); const showWorkspaceForm = ref(false); const showTaskForm = ref(false); const providerTemplate = ref<'local' | 'deepseek' | 'custom'>('local')
const deploymentStorageKey = 'simplenessagent.selected-deployment-id'
const selectedDeployment = computed(() => deployments.value.find((deployment) => deployment.deployment_id === selectedDeploymentID.value) ?? null)
const selectedPlanSteps = computed(() => selected.value?.plan?.steps ?? [])
const runDisabledReason = computed(() => {
  if (busy.value) return '正在处理当前任务'
  if (!selectedDeploymentID.value) return '请先选择一个模型'
  if (!selected.value) return '请先选择一个任务'
  if (selected.value.task.status !== 'READY') return `任务当前为 ${selected.value.task.status}，不能再次运行`
  return ''
})
function fail(cause: unknown) { error.value = String(cause); notice.value = ''; runPhase.value = 'idle' }
function selectDeployment(id: string) { selectedDeploymentID.value = id; capability.value = null; if (id) localStorage.setItem(deploymentStorageKey, id); else localStorage.removeItem(deploymentStorageKey) }
function applyProviderTemplate() { if (providerTemplate.value === 'deepseek') { deploymentName.value = 'DeepSeek API'; deploymentEndpoint.value = 'https://api.deepseek.com'; deploymentModel.value = 'deepseek-v4-flash' } else if (providerTemplate.value === 'local') { deploymentName.value = 'Local model'; deploymentEndpoint.value = 'http://127.0.0.1:8080/v1'; deploymentModel.value = '' } else { deploymentName.value = 'Custom OpenAI-compatible'; deploymentEndpoint.value = ''; deploymentModel.value = '' } }
async function refresh() { loading.value = true; error.value = ''; try { const [taskItems, workspaceItems, deploymentItems] = await Promise.all([window.go.main.App.ListTasks(), window.go.main.App.ListWorkspaces(), window.go.main.App.ListDeployments()]); tasks.value = taskItems as TaskSnapshot[]; workspaces.value = workspaceItems as Workspace[]; deployments.value = deploymentItems as Deployment[]; if (!taskWorkspaceID.value && workspaces.value.length) taskWorkspaceID.value = workspaces.value[0].id; if (!deployments.value.some((item) => item.deployment_id === selectedDeploymentID.value)) { const remembered = localStorage.getItem(deploymentStorageKey) ?? ''; selectDeployment(deployments.value.some((item) => item.deployment_id === remembered) ? remembered : (deployments.value[0]?.deployment_id ?? '')) }; if (selected.value) { const updated = tasks.value.find((item) => item.task.id === selected.value?.task.id); selected.value = updated ?? null }; if (!selected.value && tasks.value.length) selected.value = tasks.value[0] } catch (cause) { fail(cause) } finally { loading.value = false } }
async function createWorkspace() { try { busy.value = true; await window.go.main.App.CreateWorkspace(workspaceName.value, workspacePath.value); workspaceName.value = ''; workspacePath.value = ''; showWorkspaceForm.value = false; notice.value = '工作区已创建'; await refresh() } catch (cause) { fail(cause) } finally { busy.value = false } }
async function createTask() { try { busy.value = true; selected.value = await window.go.main.App.CreateTask(taskWorkspaceID.value, taskTitle.value, taskGoal.value) as TaskSnapshot; taskTitle.value = ''; taskGoal.value = ''; showTaskForm.value = false; notice.value = '任务已创建，可以开始运行'; await refresh() } catch (cause) { fail(cause) } finally { busy.value = false } }
async function configureModel() { try { busy.value = true; const item = await window.go.main.App.ConfigureOpenAICompatibleDeployment(deploymentName.value, deploymentEndpoint.value, deploymentModel.value, apiKey.value) as Deployment; selectDeployment(item.deployment_id); apiKey.value = ''; notice.value = '模型已保存并选中'; await refresh() } catch (cause) { fail(cause) } finally { busy.value = false } }
async function probeModel() { try { busy.value = true; capability.value = await window.go.main.App.ProbeDeployment(selectedDeploymentID.value) as Capability; notice.value = '能力检查完成' } catch (cause) { fail(cause) } finally { busy.value = false } }
async function selectTask(id: string) { try { selected.value = await window.go.main.App.GetTaskSnapshot(id) as TaskSnapshot; error.value = ''; notice.value = '' } catch (cause) { fail(cause) } }
async function runAgent() { if (runDisabledReason.value || !selected.value) return; const taskID = selected.value.task.id; try { busy.value = true; error.value = ''; runPhase.value = 'planning'; notice.value = '正在请求模型生成受控计划…'; await window.go.main.App.GeneratePlan(taskID, selectedDeploymentID.value); selected.value = await window.go.main.App.GetTaskSnapshot(taskID) as TaskSnapshot; runPhase.value = 'running'; notice.value = `计划已生成，正在执行 ${selectedPlanSteps.value.length} 个步骤…`; selected.value = await window.go.main.App.RunAgent(taskID, selectedDeploymentID.value) as TaskSnapshot; notice.value = 'Agent 已完成执行，结果已写入任务记录' } catch (cause) { try { selected.value = await window.go.main.App.GetTaskSnapshot(taskID) as TaskSnapshot } catch { /* preserve the original error */ }; fail(cause) } finally { busy.value = false; runPhase.value = 'idle'; await refresh() } }
function phaseLabel(index: number) { if (runPhase.value === 'planning' && index === 1) return '进行中'; if (runPhase.value === 'running' && index === 2) return '进行中'; if (index === 1 && selectedPlanSteps.value.length) return '已完成'; if (index === 2 && selected.value?.task.status === 'COMPLETED') return '已完成'; return index === 0 ? '已完成' : '等待中' }
onMounted(refresh)
</script>

<template>
  <div class="app-shell">
    <aside class="sidebar"><div class="brand"><div class="brand-mark">S</div><div><strong>Simpleness</strong><small>Agent Studio</small></div></div><nav><button :class="{ active: activePanel === 'tasks' }" @click="activePanel = 'tasks'"><span>◉</span>任务中心</button><button :class="{ active: activePanel === 'settings' }" @click="activePanel = 'settings'"><span>◇</span>模型与设置</button></nav><div class="sidebar-status"><i></i>Core 已连接</div></aside>
    <main class="main"><header class="topbar"><div><p class="eyebrow">{{ activePanel === 'tasks' ? 'TASK ORCHESTRATION' : 'MODEL CONTROL PLANE' }}</p><h1>{{ activePanel === 'tasks' ? '任务工作台' : '模型与工作区' }}</h1></div><div class="model-picker"><select :value="selectedDeploymentID" @change="selectDeployment(($event.target as HTMLSelectElement).value)"><option disabled value="">选择模型</option><option v-for="item in deployments" :key="item.deployment_id" :value="item.deployment_id">{{ item.name }} · {{ item.model }}</option></select><button class="button ghost" :disabled="busy" @click="refresh">刷新</button></div></header>
      <div v-if="notice" class="banner success">{{ notice }}</div><div v-if="error" class="banner danger"><b>执行未完成</b><span>{{ error }}</span></div>
      <section v-if="activePanel === 'settings'" class="settings"><article class="card settings-card"><div class="card-heading"><div><p class="eyebrow">PROVIDER</p><h2>模型配置</h2></div><span class="tag">安全凭据</span></div><form class="form-grid" @submit.prevent="configureModel"><label>快速模板<select v-model="providerTemplate" @change="applyProviderTemplate"><option value="local">本地模型</option><option value="deepseek">DeepSeek API</option><option value="custom">自定义 OpenAI-compatible</option></select></label><p v-if="providerTemplate === 'deepseek'" class="hint">已预填 DeepSeek 地址和模型；填写 API Key 后保存即可。</p><label>配置名称<input v-model="deploymentName" required></label><label>Base URL<input v-model="deploymentEndpoint" required></label><label>模型 ID<input v-model="deploymentModel" required></label><label>API Key <small>保存在 Windows 凭据管理器，不写入 SQLite</small><input v-model="apiKey" type="password" placeholder="sk-…"></label><button class="button primary" :disabled="busy">保存模型</button></form></article><article class="card settings-card"><div class="card-heading"><div><p class="eyebrow">RUNTIME</p><h2>能力检查</h2></div></div><div class="selected-model"><b>{{ selectedDeployment?.name ?? '尚未选择模型' }}</b><small>{{ selectedDeployment ? `${selectedDeployment.model} · ${selectedDeployment.endpoint}` : '保存或从顶部选择模型' }}</small></div><button class="button secondary" :disabled="busy || !selectedDeploymentID" @click="probeModel">检查连通性与能力</button><div v-if="capability" class="capability-list"><span>流式输出 <b>{{ capability.supports_streaming ? '支持' : '未支持' }}</b></span><span>工具调用 <b>{{ capability.supports_tools ? '支持' : '未支持' }}</b></span><span>上下文窗口 <b>{{ capability.reliable_context_tokens || '未报告' }}</b></span></div></article><article class="card workspace-card"><div class="card-heading"><div><p class="eyebrow">SCOPE</p><h2>已授权工作区</h2></div><button class="link-button" @click="showWorkspaceForm = !showWorkspaceForm">添加工作区</button></div><form v-if="showWorkspaceForm" class="workspace-form" @submit.prevent="createWorkspace"><input v-model="workspaceName" placeholder="显示名称（可选）"><input v-model="workspacePath" required placeholder="本地目录绝对路径"><button class="button secondary" :disabled="busy">授权目录</button></form><div class="workspace-list"><div v-for="item in workspaces" :key="item.id"><b>{{ item.name }}</b><small>{{ item.root_path }}</small></div><p v-if="!workspaces.length">尚未添加工作区。</p></div></article></section>
      <section v-else class="task-layout"><aside class="card task-list-card"><div class="section-top"><div><p class="eyebrow">TASKS</p><h2>任务</h2></div><button class="add-button" @click="showTaskForm = !showTaskForm">+</button></div><form v-if="showTaskForm" class="new-task" @submit.prevent="createTask"><select v-model="taskWorkspaceID" required><option disabled value="">选择工作区</option><option v-for="item in workspaces" :key="item.id" :value="item.id">{{ item.name }}</option></select><input v-model="taskTitle" required placeholder="任务标题"><textarea v-model="taskGoal" required placeholder="希望 Agent 完成什么？"></textarea><button class="button primary" :disabled="busy">创建任务</button></form><p v-if="loading" class="empty-copy">同步中…</p><div v-else class="task-list"><button v-for="item in tasks" :key="item.task.id" :class="{ selected: selected?.task.id === item.task.id }" @click="selectTask(item.task.id)"><i :class="item.task.status.toLowerCase()"></i><span><b>{{ item.task.title }}</b><small>{{ item.task.goal }}</small><em>{{ item.task.status }}</em></span></button><p v-if="!tasks.length" class="empty-copy">创建一个任务，开始你的第一轮 Agent 执行。</p></div></aside>
        <section v-if="selected" class="task-detail"><article class="card task-hero"><div class="task-summary"><p class="eyebrow">{{ selected.task.status }}</p><h2>{{ selected.task.title }}</h2><p>{{ selected.task.goal }}</p><div class="model-chip">模型：{{ selectedDeployment?.name ?? '未选择' }} · {{ selectedDeployment?.model ?? '—' }}</div></div><div class="run-area"><button class="button run-button" :disabled="!!runDisabledReason" @click="runAgent">{{ busy ? (runPhase === 'planning' ? '正在生成计划…' : '正在执行…') : '运行 Agent' }}</button><small>{{ runDisabledReason || '先生成受控计划，再执行只读步骤并保存证据。' }}</small></div></article><article class="card process-card"><div class="section-top"><div><p class="eyebrow">EXECUTION</p><h2>执行进度</h2></div><span class="tag">{{ selectedPlanSteps.length ? `${selectedPlanSteps.length} 个步骤` : '尚未计划' }}</span></div><div class="phase-row"><div v-for="(label, index) in ['任务创建', '生成计划', '执行与验证']" :key="label" class="phase" :class="{ done: phaseLabel(index) === '已完成', active: phaseLabel(index) === '进行中' }"><i>{{ index + 1 }}</i><span><b>{{ label }}</b><small>{{ phaseLabel(index) }}</small></span></div></div></article><article class="card plan-card"><div class="section-top"><div><p class="eyebrow">PLAN & RESULTS</p><h2>{{ selected.plan?.summary || '等待生成计划' }}</h2></div><span v-if="selected.plan?.revision" class="tag">修订 {{ selected.plan.revision }}</span></div><div v-if="selectedPlanSteps.length" class="step-list"><div v-for="step in selectedPlanSteps" :key="step.step_id" class="step-row"><i :class="selected.steps.find((runtime) => runtime.step_id === step.step_id)?.status?.toLowerCase() ?? 'pending'"></i><div><b>{{ step.title }}</b><p>{{ step.goal }}</p><small>{{ step.allowed_tools.join(' · ') || '无工具调用' }}</small></div><span class="step-status">{{ selected.steps.find((runtime) => runtime.step_id === step.step_id)?.status ?? 'PENDING' }}</span></div></div><div v-else class="empty-plan"><b>还没有计划</b><p>点击“运行 Agent”后，模型生成的计划和每个步骤都会显示在这里。</p></div></article></section><section v-else class="card blank-detail"><h2>选择一个任务</h2><p>在左侧选择已有任务，或创建新任务开始执行。</p></section>
        <aside class="card activity-card"><div class="section-top"><div><p class="eyebrow">AUDIT TRAIL</p><h2>活动记录</h2></div></div><div v-if="selected?.events?.length" class="event-list"><div v-for="event in selected.events.slice().reverse().slice(0, 10)" :key="event.sequence"><i></i><span><b>{{ event.event_type.replaceAll('_', ' ') }}</b><small>{{ event.timestamp }}</small></span></div></div><p v-else class="empty-copy">执行后将在此保留事件记录。</p></aside>
      </section>
    </main>
  </div>
</template>
