// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {contracts} from '../models';
import {app} from '../models';
import {main} from '../models';

export function ConfigureOpenAICompatibleDeployment(arg1:string,arg2:string,arg3:string,arg4:string):Promise<contracts.Deployment>;

export function CreateTask(arg1:string,arg2:string,arg3:string):Promise<app.TaskSnapshot>;

export function CreateWorkspace(arg1:string,arg2:string):Promise<contracts.Workspace>;

export function DataDir():Promise<string>;

export function GeneratePlan(arg1:string,arg2:string):Promise<contracts.PlanVersion>;

export function GetConversation(arg1:string):Promise<main.ConversationView>;

export function GetTaskSnapshot(arg1:string):Promise<app.TaskSnapshot>;

export function ListConversations():Promise<Array<contracts.Task>>;

export function ListDeployments():Promise<Array<contracts.Deployment>>;

export function ListTasks():Promise<Array<app.TaskSnapshot>>;

export function ListWorkspaces():Promise<Array<contracts.Workspace>>;

export function ProbeDeployment(arg1:string):Promise<contracts.CapabilitySnapshot>;

export function RunAgent(arg1:string,arg2:string):Promise<app.TaskSnapshot>;

export function SendConversationMessage(arg1:string,arg2:string,arg3:string):Promise<main.ConversationView>;

export function StartConversation(arg1:string,arg2:string,arg3:string):Promise<main.ConversationView>;
