// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {contracts} from '../models';
import {app} from '../models';
import {diagnostics} from '../models';

export function AdvanceLongConversation(arg1:string):Promise<main.LongConversationCycle>;

export function ApproveConversationCommand(arg1:string,arg2:string):Promise<main.ConversationView>;

export function ApproveConversationWrite(arg1:string,arg2:string):Promise<main.ConversationView>;

export function CancelLongConversation(arg1:string):Promise<contracts.HorizonState>;

export function ConfigureOpenAICompatibleDeployment(arg1:string,arg2:string,arg3:string,arg4:string):Promise<contracts.Deployment>;

export function CreateTask(arg1:string,arg2:string,arg3:string):Promise<app.TaskSnapshot>;

export function CreateWorkspace(arg1:string,arg2:string):Promise<contracts.Workspace>;

export function DataDir():Promise<string>;

export function GeneratePlan(arg1:string,arg2:string):Promise<contracts.PlanVersion>;

export function GetConversation(arg1:string):Promise<main.ConversationView>;

export function GetLongHorizonStatus(arg1:string):Promise<contracts.HorizonState>;

export function GetTaskPlan(arg1:string):Promise<main.PlanViewData>;

export function GetTaskSnapshot(arg1:string):Promise<app.TaskSnapshot>;

export function ListConversations():Promise<Array<contracts.Task>>;

export function ListDeployments():Promise<Array<contracts.Deployment>>;

export function ListDiagnosticLogs(arg1:number):Promise<Array<diagnostics.Entry>>;

export function ListTaskArtifacts(arg1:string):Promise<Array<contracts.Artifact>>;

export function ListTasks():Promise<Array<app.TaskSnapshot>>;

export function ListWorkspaces():Promise<Array<contracts.Workspace>>;

export function ProbeDeployment(arg1:string):Promise<contracts.CapabilitySnapshot>;

export function ReadTaskArtifact(arg1:string,arg2:string):Promise<string>;

export function RecordClientLog(arg1:string,arg2:string,arg3:Record<string, string>):Promise<void>;

export function ResumeLongConversation(arg1:string):Promise<main.LongConversationCycle>;

export function RunAgent(arg1:string,arg2:string):Promise<app.TaskSnapshot>;

export function SendConversationMessage(arg1:string,arg2:string,arg3:string,arg4:string):Promise<main.ConversationView>;

export function SendLongConversationMessage(arg1:string,arg2:string,arg3:string,arg4:string):Promise<main.LongConversationCycle>;

export function StartConversation(arg1:string,arg2:string,arg3:string,arg4:string):Promise<main.ConversationView>;

export function StartLongConversation(arg1:string,arg2:string,arg3:string,arg4:string):Promise<main.LongConversationCycle>;
