// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ConfigureOpenAICompatibleDeployment(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['ConfigureOpenAICompatibleDeployment'](arg1, arg2, arg3, arg4);
}

export function CreateTask(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreateTask'](arg1, arg2, arg3);
}

export function CreateWorkspace(arg1, arg2) {
  return window['go']['main']['App']['CreateWorkspace'](arg1, arg2);
}

export function DataDir() {
  return window['go']['main']['App']['DataDir']();
}

export function GeneratePlan(arg1, arg2) {
  return window['go']['main']['App']['GeneratePlan'](arg1, arg2);
}

export function GetTaskSnapshot(arg1) {
  return window['go']['main']['App']['GetTaskSnapshot'](arg1);
}

export function ListDeployments() {
  return window['go']['main']['App']['ListDeployments']();
}

export function ListTasks() {
  return window['go']['main']['App']['ListTasks']();
}

export function ListWorkspaces() {
  return window['go']['main']['App']['ListWorkspaces']();
}

export function ProbeDeployment(arg1) {
  return window['go']['main']['App']['ProbeDeployment'](arg1);
}

export function RunAgent(arg1, arg2) {
  return window['go']['main']['App']['RunAgent'](arg1, arg2);
}
