// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AdvanceLongConversation(arg1) {
  return window['go']['main']['App']['AdvanceLongConversation'](arg1);
}

export function ApproveConversationCommand(arg1, arg2) {
  return window['go']['main']['App']['ApproveConversationCommand'](arg1, arg2);
}

export function ApproveConversationWrite(arg1, arg2) {
  return window['go']['main']['App']['ApproveConversationWrite'](arg1, arg2);
}

export function CancelLongConversation(arg1) {
  return window['go']['main']['App']['CancelLongConversation'](arg1);
}

export function ConfigureOpenAICompatibleDeployment(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['ConfigureOpenAICompatibleDeployment'](arg1, arg2, arg3, arg4);
}

export function CreateTask(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreateTask'](arg1, arg2, arg3);
}

export function CreateWorkspace(arg1, arg2) {
  return window['go']['main']['App']['CreateWorkspace'](arg1, arg2);
}

export function DataDir() {
  return window['go']['main']['App']['DataDir']();
}

export function GeneratePlan(arg1, arg2) {
  return window['go']['main']['App']['GeneratePlan'](arg1, arg2);
}

export function GetConversation(arg1) {
  return window['go']['main']['App']['GetConversation'](arg1);
}

export function GetLongHorizonStatus(arg1) {
  return window['go']['main']['App']['GetLongHorizonStatus'](arg1);
}

export function GetTaskPlan(arg1) {
  return window['go']['main']['App']['GetTaskPlan'](arg1);
}

export function GetTaskSnapshot(arg1) {
  return window['go']['main']['App']['GetTaskSnapshot'](arg1);
}

export function ListConversations() {
  return window['go']['main']['App']['ListConversations']();
}

export function ListDeployments() {
  return window['go']['main']['App']['ListDeployments']();
}

export function ListDiagnosticLogs(arg1) {
  return window['go']['main']['App']['ListDiagnosticLogs'](arg1);
}

export function ListTaskArtifacts(arg1) {
  return window['go']['main']['App']['ListTaskArtifacts'](arg1);
}

export function ListTasks() {
  return window['go']['main']['App']['ListTasks']();
}

export function ListWorkspaces() {
  return window['go']['main']['App']['ListWorkspaces']();
}

export function ProbeDeployment(arg1) {
  return window['go']['main']['App']['ProbeDeployment'](arg1);
}

export function ReadTaskArtifact(arg1, arg2) {
  return window['go']['main']['App']['ReadTaskArtifact'](arg1, arg2);
}

export function RecordClientLog(arg1, arg2, arg3) {
  return window['go']['main']['App']['RecordClientLog'](arg1, arg2, arg3);
}

export function ResumeLongConversation(arg1) {
  return window['go']['main']['App']['ResumeLongConversation'](arg1);
}

export function RunAgent(arg1, arg2) {
  return window['go']['main']['App']['RunAgent'](arg1, arg2);
}

export function SendConversationMessage(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SendConversationMessage'](arg1, arg2, arg3, arg4);
}

export function SendLongConversationMessage(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SendLongConversationMessage'](arg1, arg2, arg3, arg4);
}

export function StartConversation(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['StartConversation'](arg1, arg2, arg3, arg4);
}

export function StartLongConversation(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['StartLongConversation'](arg1, arg2, arg3, arg4);
}
